In [2]:
import numpy as np

In [3]:
list=[1,2,3,4,5]
arr=np.array(list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [23]:
#Multinested array
l1=[1,2,3,4,5]
l2=[2,3,5,6,8]
l3=[9,8,7,6,5]
arr=np.array([l1,l2,l3])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 8],
       [9, 8, 7, 6, 5]])

In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 5, 6],
       [8, 9, 8],
       [7, 6, 5]])

In [15]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 8],
       [9, 8, 7, 6, 5]])

Indexing

In [30]:
arr=np.array([1,2,3,5,6,7,8,8])
arr[3]

np.int64(5)

In [19]:
arr[::]

array([1, 2, 3, 5, 6, 7, 8, 8])

In [20]:
arr[:-1]

array([1, 2, 3, 5, 6, 7, 8])

In [21]:
arr[:-4]

array([1, 2, 3, 5])

In [22]:
arr

array([1, 2, 3, 5, 6, 7, 8, 8])

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 8],
       [9, 8, 7, 6, 5]])

In [25]:
arr[:,3:]

array([[4, 5],
       [6, 8],
       [6, 5]])

In [26]:
arr=np.arange(0,10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[3:]=999
arr

array([  1,   2,   3, 999, 999, 999, 999, 999])

In [35]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [37]:
#copy() function and broadcasting
arr1=arr.copy()

In [38]:
arr1

array([  1,   2,   3, 999, 999, 999, 999, 999])

In [39]:
#random distribution
np.random.rand(3,3)

array([[0.28636584, 0.61660796, 0.92832384],
       [0.17479118, 0.11045215, 0.70079817],
       [0.67500282, 0.47730406, 0.372581  ]])

In [40]:
arr_ex=np.random.randn(4,4)

In [41]:
arr_ex

array([[-0.03524505,  0.10425204, -0.55992886, -0.98109424],
       [-1.22189887, -0.5260773 , -0.15529239,  0.60133891],
       [-1.24193582,  0.83461205,  0.72727267,  0.65345204],
       [ 1.79250981, -0.76644976,  0.58833073,  2.2153488 ]])

In [45]:
np.random.randint(0,100,8).reshape(2,4)

array([[12, 91, 67,  0],
       [36, 14,  5, 80]])

In [49]:
np.random.random_sample((1,5))

array([[0.25079641, 0.41611222, 0.75429533, 0.09867392, 0.53702049]])